/**
 * Types
 */

export const CONNECT_WEBSOCKET = 'WEBSOCKET_CONNECT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVED_MESSAGE';
export const CHANGE_TCHAT_INPUT = 'CHANGE_TCHAT_INPUT';
export const CHANGE_LOGIN_INPUT = 'CHANGE_LOGIN_INPUT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CONNECT_USER = 'CONNECT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const TEXT_COLOR = 'TEXT_COLOR';
export const ADD_EMOJI = 'ADD_EMOJI';
export const CLEAR_INPUT = 'CLEAR_INPUT';
